services:
  - type: web
    name: hantavirusspread
    runtime: node
    plan: free
    branch: main
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
